<div>
{include file="CRM/common/formButtons.tpl" location="top"}
</div>

<h3>This new form is generated by <?php echo $namespace ?>/Form/<?php echo $formClassName ?>.php</h3>

{$form.favorite_color.label} {$form.favorite_color.html}

<div>
{include file="CRM/common/formButtons.tpl" location="bottom"}
</div>